version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      # Your existing credentials
      - POSTGRES_USER=fbcalderaro
      - POSTGRES_PASSWORD=123tusca
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    volumes:
      # Mount the persistent data volume
      - ./postgres-data:/var/lib/postgresql/data
      # Mount your local backup folder to /db_backups inside the container
      - ./db-backup:/db-backups
      # Mount the init script to the special directory
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    restart: always
    environment:
      # Pass the GitHub repo URL to the entrypoint script
      - GIT_REPO_URL=https://github.com/your-username/your-repo.git # <-- CHANGE THIS
      # Your other environment variables for DB connection, etc.
      # ...
    volumes:
      # Mount a volume for the code to persist it between container restarts
      - ./python_code:/usr/src/app/python-scripts
    depends_on:
      - db