version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=fbcalderaro
      - POSTGRES_PASSWORD=123tusca
      - POSTGRES_DB=crypto_trading
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db-backup:/db-backups
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    restart: always
    environment:
      # --- For Database Connection ---
      - DB_USER=fbcalderaro
      - DB_PASSWORD=123tusca
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=crypto_trading
    volumes:
      # Mount the entire project directory into the container's /app folder
      - .:/app
    depends_on:
      - db
    env_file:
      - .env