version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=fbcalderaro
      - POSTGRES_PASSWORD=123tusca
      - POSTGRES_DB=crypto_trading
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db-backup:/db-backups
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    restart: always
    environment:
      - GIT_REPO_URL=https://github.com/fbcalderaro/cqf-final-project.git
      # Your other environment variables for DB connection, etc.
      # ...
    volumes:
      # Mount the entire project directory into /app
      - .:/app
    depends_on:
      - db