# /trading_system/config/config.yaml

system:
  initial_cash: 100000.0                # Starting cash for paper trading.
  commission_pct: 0.001                 # 0.1% commission per trade.
  risk_per_trade_pct: 0.50              # Percentage of total equity to risk per trade.
  reconciliation_interval_seconds: 60   # How often to check broker vs internal state.
  master_monitor_interval_seconds: 60   # How often to save the master portfolio summary for the dashboard.
  dashboard_interval_seconds: 60        # How often to regenerate the main dashboard HTML file.
  trading_mode: "live"                  # Options: "live" or "paper"

  # --- Execution Control Parameters ---
  paper_slippage_pct: 0.0005            # 0.05% simulated slippage for paper trading.
  max_impact_slippage_pct: 0.2          # Max allowed slippage from book depth impact (as %).
  order_verify_retries: 3               # Number of times to re-check an order's status.
  order_verify_delay_seconds: 2         # Seconds to wait between verification attempts.

  # --- Database Configuration ---
  database:
    host: "db"
    port: 5432
    name: "crypto_trading_db"
    user: "trading_user"
    password: "a_secure_password"

# --- Data Ingestion Configuration ---
data_ingestion:
  assets_to_track: # List of assets to track and store data for. The script will create a table for each.
    - "BTC-USDT"
    - "ETH-USDT" # Add more assets as needed
  historical_start_date: "2022-01-01" # The earliest date to backfill historical data from if the database is empty.
  base_interval: "1m" # The interval to fetch and store. Should be the lowest granularity available.

# --- Backtesting Configuration ---
backtest:
  generate_individual_reports: true
  periods:
    in_sample:
      start_date: '2025-01-01T00:00:00'
      end_date: '2025-06-30T23:59:59'
    out_of_sample:
      start_date: '2025-07-01T00:00:00'
      end_date: '2025-08-15T23:59:59'

# --- Trading Strategies Configuration ---
strategies:

  # ===================================================================
  #  Test Strategies
  # ===================================================================
  # Use this strategy to verify the live trading engine is working.
  # It will generate a BUY signal, then a SELL signal, every 'signal_interval' bars.

  # - name: "Test_Signal_Generator_1"
  #   class: "TestStrategy"
  #   module: "strategies.test_strategy" 
  #   asset: "BTC-USDT"
  #   timeframe: "1m"
  #   cash_allocation_pct: 51 # Allocate X% of total cash to this strategy
  #   params:
  #     signal_interval: 1 # Generate a signal every 1 bars of 'timeframe'
  #     hold_probability: 0.2

  # - name: "Test_Signal_Generator_2"
  #   class: "TestStrategy"
  #   module: "strategies.test_strategy" 
  #   asset: "ETH-USDT"
  #   timeframe: "1m"
  #   cash_allocation_pct: 49 # Allocate X% of total cash to this strategy
  #   params:
  #     signal_interval: 1 # Generate a signal every 1 bars of 'timeframe'
  #     hold_probability: 0.2

  # ===================================================================
  #  Momentum Strategy Variations
  # ===================================================================

  # # --- Base Strategy ---
  # - name: "Momentum_Base"
  #   class: "MomentumStrategy"
  #   module: "strategies.momentum_strategy"
  #   asset: "BTC-USDT"
  #   timeframe: "1m"
  #   params:
  #     ma_type: "ema"
  #     short_window: 20
  #     long_window: 50
  #     use_adx_filter: true
  #     adx_threshold: 25.0
  #     use_macd_filter: true

  # # --- Variation 1: Faster & More Responsive ---
  # # Hypothesis: The base strategy is too slow. A faster crossover will catch trends earlier.
  # - name: "Momentum_Faster"
  #   class: "MomentumStrategy"
  #   module: "strategies.momentum_strategy"
  #   asset: "BTC-USDT"
  #   timeframe: "1m"
  #   params:
  #     ma_type: "ema"
  #     short_window: 12      # Faster
  #     long_window: 26       # Faster
  #     use_adx_filter: true
  #     adx_threshold: 22.0   # Slightly lower threshold
  #     use_macd_filter: true

  # # --- Variation 2: Slower & More Conservative ---
  # # Hypothesis: The base strategy is too noisy. A slower crossover will only catch major, more reliable trends.
  # - name: "Momentum_Slower"
  #   class: "MomentumStrategy"
  #   module: "strategies.momentum_strategy"
  #   asset: "BTC-USDT"
  #   timeframe: "1m"
  #   cash_allocation_pct: 25 # Allocate X% of total cash to this strategy
  #   params:
  #     ma_type: "ema"
  #     short_window: 50       # Slower
  #     long_window: 100       # Slower
  #     use_adx_filter: true
  #     adx_threshold: 28.0    # Higher threshold for stronger trends
  #     use_macd_filter: true

  # --- Variation M3: No MACD Confirmation ---
  # Hypothesis: The MACD filter is too restrictive and might be filtering out good trades.
  - name: "Momentum_NoMACD"
    class: "MomentumStrategy"
    module: "strategies.momentum_strategy"
    asset: "BTC-USDT"
    timeframe: "30m"
    params:
      ma_type: "ema"
      short_window: 20
      long_window: 50
      use_adx_filter: true
      adx_threshold: 25.0
      use_macd_filter: false # Disabled MACD filter

  # # --- Variation M4: No ADX Filter ---
  # # Hypothesis: The ADX filter, while designed to trade only in trending markets, might be too conservative and filter out the beginning of strong trends.
  # - name: "Momentum_NoADX"
  #   class: "MomentumStrategy"
  #   module: "strategies.momentum_strategy"
  #   asset: "BTC-USDT"
  #   timeframe: "1m"
  #   cash_allocation_pct: 25 # Allocate X% of total cash to this strategy
  #   params:
  #     ma_type: "ema"
  #     short_window: 20
  #     long_window: 50
  #     use_adx_filter: false # Disabled ADX filter
  #     adx_threshold: 25.0   # This will be ignored but good to keep for consistency
  #     use_macd_filter: true

  # # --- Variation M5: Simple Moving Average (SMA) ---
  # # Hypothesis: Using a Simple Moving Average (SMA) instead of an EMA will be less sensitive to short-term price spikes, potentially reducing whipsaws and false signals.
  # - name: "Momentum_SMA"
  #   class: "MomentumStrategy"
  #   module: "strategies.momentum_strategy"
  #   asset: "BTC-USDT"
  #   timeframe: "1m"
  #   cash_allocation_pct: 50 # Allocate X% of total cash to this strategy
  #   params:
  #     ma_type: "sma" # Use SMA instead of EMA
  #     short_window: 20
  #     long_window: 50
  #     use_adx_filter: true
  #     adx_threshold: 25.0
  #     use_macd_filter: true

  # ===================================================================
  #  Mean Reversion Variations
  # ===================================================================

  # # --- Variation 1: Advanced with Filters ---
  # # Hypothesis: Adding volatility and trend filters will improve profitability by avoiding bad market regimes.
  # - name: "MeanReversion_Advanced"
  #   class: "MeanReversion"
  #   module: "strategies.mean_reversion_strategy"
  #   asset: "ETH-USDT"
  #   timeframe: "1m"
  #   params:
  #     lookback_window: 90
  #     entry_z_score: 2.0
  #     exit_z_score: 0.3
  #     stop_loss_z_score: 3.5      # Exit if z-score drops below -3.5

  #     kalman_process_noise: 0.00001
  #     kalman_measurement_noise: 0.0001

  #     # --- Enable Filters ---
  #     use_volatility_filter: true # Enable the ATR volatility filter
  #     atr_period: 14
  #     atr_multiplier: 1.5         # Only trade if ATR < 1.5 * its moving average

  #     use_trend_filter: true      # Enable the long-term trend filter
  #     trend_ma_period: 200        # Only take long trades if price > 200-period SMA

  # # --- Variation 2: More Sensitive Mean ---
  # # Hypothesis: The Kalman filter is too slow. A more responsive mean will catch reversions faster in a choppy market.
  # - name: "MeanReversion_SensitiveMean"
  #   class: "MeanReversion"
  #   module: "strategies.mean_reversion_strategy"
  #   asset: "ETH-USDT"
  #   timeframe: "1m"
  #   params:
  #     lookback_window: 90
  #     entry_z_score: 2.0
  #     exit_z_score: 0.3
  #     stop_loss_z_score: 3.5
  #     kalman_process_noise: 0.00008 # <-- Increased process noise for faster adaptation
  #     kalman_measurement_noise: 0.0001
  #     use_volatility_filter: true
  #     atr_period: 14
  #     atr_multiplier: 1.5
  #     use_trend_filter: true
  #     trend_ma_period: 200

  # --- Variation 3: Stricter Entry, Wider Stop ---
  # Hypothesis: Requiring a stronger deviation to enter (higher Z-score) but allowing more room before stopping out will improve the win rate.
  - name: "MeanReversion_StrictEntry"
    class: "MeanReversion"
    module: "strategies.mean_reversion_strategy"
    asset: "ETH-USDT"
    timeframe: "15m"
    cash_allocation_pct: 50
    params:
      lookback_window: 90
      entry_z_score: 2.5        # <-- Stricter entry
      exit_z_score: 0.3
      stop_loss_z_score: 4.0      # <-- Wider stop-loss
      kalman_process_noise: 0.00001
      kalman_measurement_noise: 0.0001
      use_volatility_filter: true
      atr_period: 14
      atr_multiplier: 1.5
      use_trend_filter: true
      trend_ma_period: 200

  # # --- Variation 4: Looser Volatility Filter ---
  # # Hypothesis: The volatility filter is too restrictive. Allowing trades in slightly more volatile conditions might capture more opportunities.
  # - name: "MeanReversion_LooseVolFilter"
  #   class: "MeanReversion"
  #   module: "strategies.mean_reversion_strategy"
  #   asset: "ETH-USDT"
  #   timeframe: "1m"
  #   params:
  #     lookback_window: 90
  #     entry_z_score: 2.0
  #     exit_z_score: 0.3
  #     stop_loss_z_score: 3.5
  #     kalman_process_noise: 0.00001
  #     kalman_measurement_noise: 0.0001
  #     use_volatility_filter: true
  #     atr_period: 14
  #     atr_multiplier: 2.0         # <-- Looser volatility filter
  #     use_trend_filter: true
  #     trend_ma_period: 200

  # # --- Variation 5: Faster Trend Filter ---
  # # Hypothesis: The 200-period trend filter is too slow for a 11m chart. A faster MA will align better with the strategy's holding period.
  # - name: "MeanReversion_FastTrendFilter"
  #   class: "MeanReversion"
  #   module: "strategies.mean_reversion_strategy"
  #   asset: "ETH-USDT"
  #   timeframe: "1m"
  #   cash_allocation_pct: 50 # Allocate X% of total cash to this strategy
  #   params:
  #     lookback_window: 90
  #     entry_z_score: 2.0
  #     exit_z_score: 0.3
  #     stop_loss_z_score: 3.5
  #     kalman_process_noise: 0.00001
  #     kalman_measurement_noise: 0.0001
  #     use_volatility_filter: true
  #     atr_period: 14
  #     atr_multiplier: 1.5
  #     use_trend_filter: true
  #     trend_ma_period: 100        # <-- Faster trend filter

  # # --- Variation 6: High-Frequency Filtered ---
  # # Hypothesis: A shorter lookback period combined with the safety of filters can create a robust, high-frequency strategy.
  # - name: "MeanReversion_HighFreqFiltered"
  #   class: "MeanReversion"
  #   module: "strategies.mean_reversion_strategy"
  #   asset: "ETH-USDT"
  #   timeframe: "1m"
  #   params:
  #     lookback_window: 45         # <-- Shorter lookback
  #     entry_z_score: 1.8          # Adjusted for shorter lookback
  #     exit_z_score: 0.5           # Adjusted for shorter lookback
  #     stop_loss_z_score: 3.0      # Adjusted for shorter lookback
  #     kalman_process_noise: 0.00001
  #     kalman_measurement_noise: 0.0001
  #     use_volatility_filter: true
  #     atr_period: 14
  #     atr_multiplier: 1.5
  #     use_trend_filter: true
  #     trend_ma_period: 200